# Generated by Django 5.1.2 on 2024-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(db_column='path', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'path',
            },
        ),
    ]
