# Generated by Django 5.1.3 on 2024-11-17 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('persona', models.CharField(db_column='persona', default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', default='', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('path', models.CharField(db_column='path', default='', max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
            ],
            options={
                'db_table': 'urls',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_column='uuid', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', default='', max_length=200, unique=True)),
                ('first_name', models.CharField(db_column='first_name', default='', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', default='', max_length=100)),
                ('email', models.EmailField(db_column='email', default='', max_length=256)),
                ('password', models.CharField(db_column='password', default='', max_length=256)),
                ('is_active', models.BooleanField(db_column='is_active', default=False)),
                ('last_login', models.DateTimeField(db_column='last_login', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('message', models.CharField(db_column='message', default='', max_length=256)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('user_uuid', models.ForeignKey(db_column='user_uuid', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('persona_id', models.ForeignKey(db_column='persona_id', default='', on_delete=django.db.models.deletion.CASCADE, to='app.personas')),
            ],
            options={
                'db_table': 'missions',
            },
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('report', models.CharField(db_column='report', default='', max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('mission_id', models.ForeignKey(db_column='mission_id', default='', on_delete=django.db.models.deletion.CASCADE, to='app.missions')),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('report', models.CharField(db_column='report', default='', max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('mission_id', models.ForeignKey(db_column='mission_id', default='', on_delete=django.db.models.deletion.CASCADE, to='app.missions')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Role_users',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(db_column='role_id', default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('user_uuid', models.OneToOneField(db_column='user_uuid', default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_users',
            },
        ),
        migrations.CreateModel(
            name='Url_permissions',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='updated_date')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='app.roles')),
                ('url_id', models.ManyToManyField(db_column='url_id', to='app.urls')),
            ],
            options={
                'db_table': 'url_permissions',
            },
        ),
    ]
