# Generated by Django 5.1.3 on 2024-11-27 16:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_column='username', default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.UUIDField(db_column='uuid', db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
