# Generated by Django 5.1.3 on 2024-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_users_groups_remove_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_superuser',
            field=models.BooleanField(db_column='is_superuser', default=False),
        ),
    ]
