# Generated by Django 5.1.3 on 2024-12-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='persona',
            field=models.CharField(db_column='persona', default='', max_length=256),
        ),
    ]
